---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
    component: web
spec:
  selector:
    matchLabels:
      app: devops-toolkit
      component: web
  template:
    metadata:
      labels:
        app: devops-toolkit
        component: web
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-cpu-limit: "0.5"
        config.linkerd.io/proxy-cpu-request: "0.1"
        config.linkerd.io/proxy-memory-limit: 1Gi
        config.linkerd.io/proxy-memory-request: 64Mi
    spec:
      containers:
      - name: devops-toolkit
        image: vfarcic/devops-toolkit-series:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
