apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- hpa.yaml
- canary.yaml
namespace: production
images:
- name: vfarcic/silly-demo
  newName: vfarcic/silly-demo
  newTag: 1.0.5
